#
# Format:
#
# <stage name>:
#   app: <Heroku app name>
#   stack: <Heroku stack, optional>
#   tag: <git tag pattern, optional>
#   repo: <git repository, optional>
#   config:
#     - <Heroku config:var name>: <Heroku config:var value>
#
production:
  app: rubygems-leader
  tag: production/*
  config:
    GOOGLE_ANALYTICS: "UA-12345678-1"

staging:
  app: rubygems-leader-staging
  config: &default
